# Generated by Django 5.2.4 on 2025-07-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_owner_alter_company_user'),
        ('invoice', '0013_alter_invoice_company_alter_invoice_created_by_and_more'),
        ('payments', '0002_cashledger_cashtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='cashledger',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='related_invoice',
        ),
        migrations.AddField(
            model_name='cashledger',
            name='as_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashledger',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cashledger',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashledger',
            name='ledger_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashledger',
            name='opening_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='payments.cashledger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='invoice.bankaccount'),
        ),
        migrations.AlterField(
            model_name='cashledger',
            name='current_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='balance_after_transaction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
