# Generated by Django 5.2.4 on 2025-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_cashtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
