# Generated by Django 5.2.4 on 2025-07-15 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_owner_alter_company_user'),
        ('invoice', '0013_alter_invoice_company_alter_invoice_created_by_and_more'),
        ('payments', '0004_cashtransaction_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankToBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='invoice.bankaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='invoice.bankaccount')),
            ],
        ),
    ]
