# Generated by Django 5.2.4 on 2025-07-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_owner_alter_company_user'),
        ('invoice', '0013_alter_invoice_company_alter_invoice_created_by_and_more'),
        ('payments', '0005_banktobanktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktobanktransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banktobanktransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='banktobanktransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_out', to='invoice.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktobanktransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_in', to='invoice.bankaccount'),
        ),
    ]
