# Generated by Django 5.2.4 on 2025-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_banktobanktransfer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktobanktransfer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
