# Generated by Django 5.2.4 on 2025-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
