# Generated by Django 5.2.4 on 2025-07-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_partytype_alter_party_party_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='is_active',
        ),
        migrations.AddField(
            model_name='party',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
