# Generated by Django 5.2.4 on 2025-07-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_created_at_company_updated_at'),
        ('customer', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='selected_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_customers', to='companies.company'),
        ),
    ]
