# Generated by Django 5.2.4 on 2025-07-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_owner'),
        ('staff', '0003_staffprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='role',
            new_name='job_role',
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_roles', to='companies.company'),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view_specific', models.BooleanField(default=False)),
                ('can_get_using_post', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_permissions', to='companies.company')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='staff.role')),
            ],
            options={
                'unique_together': {('job_role', 'company', 'module_name')},
            },
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
