# Generated by Django 5.2.4 on 2025-07-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_owner'),
        ('staff', '0005_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulepermission',
            old_name='module_name',
            new_name='required_module',
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('job_role', 'company', 'required_module')},
        ),
    ]
