# Generated by Django 5.2.4 on 2025-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_type',
            field=models.CharField(choices=[('with_tax', 'With Tax'), ('without_tax', 'Without Tax')], default='without_tax', max_length=20),
        ),
        migrations.RemoveField(
            model_name='item',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_rate',
        ),
    ]
