# Generated by Django 5.2.4 on 2025-07-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_owner_alter_company_user'),
        ('items', '0002_unittype_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='companies.company'),
        ),
    ]
