# Generated by Django 5.2.4 on 2025-07-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_created_at_company_updated_at'),
        ('items', '0003_item_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tax',
            new_name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='item',
            name='tax_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='companies.company'),
        ),
    ]
