# Generated by Django 5.2.4 on 2025-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_created_by_item_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_percent',
            field=models.FloatField(),
        ),
    ]
