# Generated by Django 5.2.4 on 2025-07-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'gst_number')},
        ),
    ]
