# Generated by Django 5.2.4 on 2025-07-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_active_gst',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_active_phone',
        ),
    ]
