# Generated by Django 5.2.4 on 2025-07-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_unique_together'),
        ('customer', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='customer.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'gst_number', 'owner')},
        ),
    ]
