# Generated by Django 5.2.4 on 2025-07-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_unique_together_company_owner_and_more'),
        ('customer', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'gst_number')},
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='customer.customer'),
            preserve_default=False,
        ),
    ]
