# Generated by Django 5.2.4 on 2025-07-06 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_is_active_alter_company_gst_number_and_more'),
        ('customer', '0003_customer_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('gst_number',), name='unique_active_gst'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('phone',), name='unique_active_phone'),
        ),
    ]
