# Generated by Django 5.2.4 on 2025-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoicetype_remove_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
