# Generated by Django 5.2.4 on 2025-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
