# Generated by Django 5.2.4 on 2025-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_paymentmode_paymentstatus_paymenttype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankTransaction',
        ),
    ]
