# Generated by Django 5.2.4 on 2025-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_delete_banktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_modes',
            field=models.ManyToManyField(blank=True, to='invoice.paymentmode'),
        ),
    ]
