# Generated by Django 5.2.4 on 2025-07-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_remove_invoice_payment_mode_invoice_payment_modes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_modes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.paymentmode'),
        ),
    ]
