# Generated by Django 5.2.4 on 2025-07-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_cashledger_cashtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='related_invoice',
        ),
        migrations.DeleteModel(
            name='CashLedger',
        ),
        migrations.DeleteModel(
            name='CashTransaction',
        ),
    ]
